#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "azuracast"
name = "AzuraCast"
description.en = "Self-hosted web radio management suite with Docker"
description.fr = "Suite de gestion de webradio auto-hébergée avec Docker"

version = "0.21.0~ynh1"

maintainers = ["YunoHost Community"]

[upstream]
license = "Apache-2.0"
website = "https://www.azuracast.com/"
demo = "https://demo.azuracast.com/"
admindoc = "https://www.azuracast.com/docs/"
userdoc = "https://www.azuracast.com/docs/"
code = "https://github.com/AzuraCast/AzuraCast"
cpe = "cpe:2.3:a:azuracast:azuracast"
fund = "https://opencollective.com/azuracast"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

# Docker-based app - limited integration with YunoHost features
ldap = false
sso = false

# AzuraCast resource requirements
disk = "2G"
ram.build = "2G"
ram.runtime = "1G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Admin password for AzuraCast web interface"
    help.fr = "Mot de passe administrateur pour l'interface web d'AzuraCast"
    type = "password"

    [install.enable_https]
    ask.en = "Enable HTTPS with Let's Encrypt?"
    ask.fr = "Activer HTTPS avec Let's Encrypt ?"
    type = "boolean"
    default = true

    [install.station_ports]
    ask.en = "Number of radio stations (ports 8000-80xx will be used)"
    ask.fr = "Nombre de stations radio (les ports 8000-80xx seront utilisés)"
    type = "number"
    min = 1
    max = 50
    default = 5

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/AzuraCast/AzuraCast/archive/refs/tags/0.21.0.zip"
    sha256 = "6a3d8b3816f97dfba45d3adb1a9649b65707d0dc94695477e5c50af2859dbd1a"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 80

    [resources.apt]
    packages = "curl, git"